sudo: false
language: node_js
node_js: '10'
cache:
  directories:
    - node_modules
    - '$HOME/.npm'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      # needed by nodegit (repo-cooker)
      - libstdc++-4.9-dev
git:
  depth: 9999
notifications:
  email: false
script:
  - |
    if [[ $SKIP_TESTS != 'true' ]]; then
      npm prune
      npm run checkdeps
      npm run lint
      npm test -- --no-parallel
    fi
after_success:
  # Adapt this to your needs.
  # Set REPO_COOKER_GITHUB_TOKEN to your GitHub personal access token in the Travis settings of your repo.
  # Set NPM_TOKEN to your npm access token in the Travis settings of your repo.
  # Replace %YourUsername%, %YourMonoRepo% and %YourEmail% with your GitHub values.
  - |
    if [[ $TRAVIS_SECURE_ENV_VARS == 'true' ]]; then
        git remote set-url origin https://%YourUsername%:${REPO_COOKER_GITHUB_TOKEN}@github.com/%YourUsername%/%YourMonoRepo%;
        git config --global user.email "%YourEmail%";
    fi
    if [[ $TRAVIS_BRANCH == 'master' || $TRAVIS_BRANCH == 'next' ]] && [[ $TRAVIS_PULL_REQUEST == 'false' ]]; then
      printf "//registry.npmjs.org/:_authToken=$NPM_TOKEN\n" > ~/.npmrc
      npm install --no-save nodegit@0.24.3
      npm run release -- --no-parallel
    fi
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
